routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::middleware(['auth', 'web'])->group(function () {
	Route::get('/', 'HomeController@index')->name('home');
	Route::resource('admin_user', '\App\Http\Controllers\Admin\AdminUser\AdminController');
	Route::resource('article', '\App\Http\Controllers\Admin\Article\ArticleController');
	Route::resource('category', '\App\Http\Controllers\Admin\Category\CategoryController');
	Route::resource('slider', '\App\Http\Controllers\Admin\Slider\SliderController');
	Route::resource('video', '\App\Http\Controllers\Admin\Video\VideoController');
	Route::resource('big_article', '\App\Http\Controllers\Admin\BigArticle\BigArticleController');
	Route::resource('event', '\App\Http\Controllers\Admin\Event\EventController');

	Route::get('get_tab/{id}/{tab_id}/edit/','\App\Http\Controllers\Admin\Event\Tab\TabController@edit')->name('tab.get');
	Route::get('tab/create/{event_id}','\App\Http\Controllers\Admin\Event\Tab\TabController@create')->name('tab.create');
	Route::post('tab/store/{event_id}', '\App\Http\Controllers\Admin\Event\Tab\TabController@store')->name('tab.store');
  //Route::match(['put', 'patch'], 'update_tab/{id}/{tab_id}','\App\Http\Controllers\Admin\Event\Tab\TabController@update')->name('tab.update');
  	Route::post('update_tab/{id}/{tab_id}','\App\Http\Controllers\Admin\Event\Tab\TabController@update')->name('tab.update');

	Route::match(['delete'], 'delete_tab/{event_id}/{tab_id}', '\App\Http\Controllers\Admin\Event\Tab\TabController@destroy')->name('tab.destroy');
});

app/Article.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;
use MongoDB\BSON\UTCDateTime;

class Article extends Model 
{
  protected $table = 'articles';

  protected $fillable = [
  	'type','category','subcategory','title','caption','content','image','published_datetime','writer','status','columns','date','parent_id','tag','header_type'
  ];
  public static function getTypeArticle(){
  	return Article::where('type','article')->orderBy('_id','desc')->get();
  }
}

app/Http/Controllers/Admin/Article/ArticleController.php
<?php

namespace App\Http\Controllers\Admin\Article;
use Illuminate\Http\Request;
use App\Article;
use App\Category;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\Controller;
use File;
use Illuminate\Support\Facades\Input;
use MongoDB\BSON\UTCDateTime;

use App\Http\Requests\RequestArticle;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::getTypeArticle();
        return view('admin.article.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.article.add',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestArticle $request)
    {
        $inputs = Input::all();
        $year = date('Y', time());
        $month = date('m', time());
        if($request->date){
        $milliseconds_date = strtotime($request->date);
        $inputs['date'] = new \MongoDB\BSON\UTCDateTime($milliseconds_date *1000);
        }
        $inputs['content'] = $request->mce_0;
        $inputs['type'] = 'article';
        if($request->hasFile('image')){
          $image = $request->file('image');
          $name = $image->getClientOriginalName();
          $format_folder = $year .'/'.  $month;
          $image_store = $image->storeAs($format_folder . '/', $name , 'pocarisweat');
          $inputs['image'] =  $format_folder . '/' . $name;
        }
        Article::create($inputs);
        return Redirect::route('article.index')->with('message', 'Successful Add New Article');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::where('_id','=', $id)->first();
        $utcdatetime = $article->date;
        $datetime = $utcdatetime->toDateTime();
        $time = $datetime->format('m/d/Y H:m:s');
        $article->date = $time;
        $categories = Category::all();
        return view('admin.article.edit',compact('article','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RequestArticle $request, $id)
    {
        $article = Article::where('_id', '=',$id)->first();
        $inputs = Input::all();
        $year = date('Y', time());
        $month = date('m', time());
        if($request->date){
        $milliseconds_date = strtotime($request->date);
        $inputs['date'] = new \MongoDB\BSON\UTCDateTime($milliseconds_date *1000);
        }
        $inputs['content'] = $request->mce_0;
        if($request->hasFile('image')){
          if($article->image){
            $old_image = $article->image;
            if($old_image){
              $article = Article::findOrFail($id);
              #File::delete('../../api/public/uploads/' . $article->image);
            }
          }
          $image = $request->file('image');
          $name = $image->getClientOriginalName();
          $format_folder = $year .'/'.  $month;
          $image_store = $image->storeAs($format_folder . '/', $name , 'pocarisweat');
          $inputs['image'] =  $format_folder . '/' . $name;
        }
        $article->update($inputs);
        return Redirect::route('article.index')->with('message', 'Successful Edit Article : ' . $article->title);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::where('_id', '=',$id)->first();
        if($article->image){
          $old_image = $article->image;
          if($old_image){
            $article = Article::findOrFail($id);
            #File::delete('../../api/public/uploads/' . $article->image);
          }
        }        
        Article::destroy($id);
        return Redirect::route('article.index')->with('message', 'Successful Delete Article');
    }
}

resources/views/admin/article/add.blade.php
@extends('admin.master.main')

@section('content')
<div class="title-block">
  <h1 class="title"> Create Article</h1>
  <p class="title-description"></p>
</div>
@if(session('message'))
    <br/>
  <div class="alert alert-success">
      {{session('message')}}
  </div>
  <br/>
@endif
@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif
<section class="section">
  <div class="row sameheight-container">
    <div class="container-fluid">
        <div class="card card-block">
          <form action="{{action ('Admin\Article\ArticleController@store')}}" enctype="multipart/form-data" method="POST" role="form">
            {!! csrf_field() !!}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Title</label>
                  <input type="text" name="title" placeholder="" class="form-control underlined" value=""> 
                </div>
                <div class="form-group">
                  <label class="control-label">Category</label>
                  <select name="category" class="selector_noxus">
                    <option value="" selected>Select Your Category</option>
                    @foreach($categories as $category)
                    <option value="{{$category->name}}">{{$category->name}}</option>
                    @endforeach
                  </select>
                </div>
                <div class="form-group">
                  <label class="control-label">Date</label>
                  <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <input  name="date" value="" class="form-control datetimepicker-input underlined" data-target="#datetimepicker1"  />
                    <span class="input-group-addon" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <span class="fa fa-calendar"></span>
                    </span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Caption</label>
                  <input type="text" name="caption" placeholder="" class="form-control underlined" value=""> 
                </div>
                <div class="form-group">
                  <label class="control-label">Tag</label>
                  <input type="text" name="tag" placeholder="" class="form-control underlined" value=""> 
                </div>
                <div class="form-group">
                  <label class="control-label">Writer</label>
                  <input type="text" name="writer[name]" placeholder="" class="form-control underlined" value=""> 
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label">Content</label>
                  <div name="content" class="editor_noxus"></div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Columns</label>
                  <select name="columns" class="selector_noxus">
                    <option value="" selected>Select Your Column Size</option>
                    <option value="big">Big</option>
                    <option value="small">Small</option>
                  </select>
                </div>
                <div class="form-group">
                  <label class="control-label">Image(1200x530)</label>
                  <input type="file" name="image" placeholder="" class="form-control underlined" value="">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Header Text</label>
                  <select name="header_type" class="selector_noxus">
                    <option value="" selected>Select Your Header Text</option>
                    <option value="text-right">text-right</option>
                    <option value="text-left">text-left</option>
                    <option value="text-center">text-center</option>
                    <option value="without-text">without-text</option>
                  </select>
                </div>
                <div class="form-group">
                  <label class="control-label">Status</label>
                  <select name="status" class="selector_noxus">
                    <option value="" selected>Select Your Status</option>
                    <option value="1">Published</option>
                    <option value="0">Unpublished</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group pull-right">
                  <button type="submit" class="btn btn-info pull-right"><em class="fa fa-check-square-o"></em> Submit</button>
                  <a href="{{ route('article.index') }}" class="btn btn-info pull-right" style="margin-right:5px;"><em class="fa fa-hand-o-left"></em> Cancel</a>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/article/edit.blade.php
@extends('admin.master.main')

@section('content')
<div class="title-block">
  <h1 class="title"> Edit Article</h1>
  <p class="title-description">Title : "{{$article->title}}"</p>
</div>
@if(session('message'))
    <br/>
  <div class="alert alert-success">
      {{session('message')}}
  </div>
  <br/>
@endif
@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif
<section class="section">
  <div class="row sameheight-container">
    <div class="container-fluid">
        <div class="card card-block">
          <form action="{{route('article.update', $article->id)}}" method="POST" enctype="multipart/form-data" role="form">
            {!! method_field('PUT') !!}
            {!! csrf_field() !!}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Title</label>
                  <input type="text" name="title" placeholder="" class="form-control underlined" value="{{ old('title',$article->title)}}"> 
                </div>
                <div class="form-group">
                  <label class="control-label">Category</label>
                  <select name="category" class="selector_noxus">
                    <option value="{{$article->category}}" selected>{{$article->category}}</option>
                    @foreach($categories as $category)
                    <option value="{{$category->name}}">{{$category->name}}</option>
                    @endforeach
                  </select>
                </div>
                <div class="form-group">
                  <label class="control-label">Date</label>
                  <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <input  name="date" value="{{ old('date',$article->date)}}" class="form-control datetimepicker-input underlined" data-target="#datetimepicker1"  />
                    <span class="input-group-addon" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <span class="fa fa-calendar"></span>
                    </span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Caption</label>
                  <input type="text" name="caption" placeholder="" class="form-control underlined" value="{{ old('caption',$article->caption)}}"> 
                </div>
                <div class="form-group">
                  <label class="control-label">Tag</label>
                  <input type="text" name="tag" placeholder="" class="form-control underlined" value="{{ old('tag',$article->tag)}}"> 
                </div>
                <div class="form-group">
                  <label class="control-label">Writer</label>
                  <input type="text" name="writer[name]" placeholder="" class="form-control underlined" value="{{$article->writer['name']}}"> 
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label">Content</label>
                  <div name="content" class="editor_noxus">{!! old('content',$article->content) !!}</div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Columns</label>
                  <select name="columns" class="selector_noxus">
                    <option value="{{old('columns',$article->columns)}}" selected>{{$article->columns}}</option>
                    <option value="big">Big</option>
                    <option value="small">Small</option>
                  </select>
                </div>
                <div class="thumb_image cont">
                  <img src="{{asset('uploads')}}/{{$article->image}}" alt="" class="thumb_image"/>
                  <span>{{$article->image}}</span>
                </div>
                <div class="form-group">
                  <label class="control-label">Image(1200x530)</label>
                  <input type="file" name="image" placeholder="" class="form-control underlined" value="">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Header Text</label>
                  <select name="header_type" class="selector_noxus">
                    <option value="{{old('header_type',$article->header_type)}}" selected>{{$article->header_type}}</option>
                    <option value="text-right">text-right</option>
                    <option value="text-left">text-left</option>
                    <option value="text-center">text-center</option>
                    <option value="without-text">without-text</option>
                  </select>
                </div>
                <div class="form-group">
                  <label class="control-label">Status</label>
                  <select name="status" class="selector_noxus">
                    <option value="{{old('status',$article->status)}}" selected>{{$article->status ? "Published" : "Unpublished"}}</option>
                    <option value="1">Published</option>
                    <option value="0">Unpublished</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group pull-right">
                  <button type="submit" class="btn btn-info pull-right"><em class="fa fa-check-square-o"></em> Submit</button>
                  <a href="{{ route('article.index') }}" class="btn btn-info pull-right" style="margin-right:5px;"><em class="fa fa-hand-o-left"></em> Cancel</a>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/article/index.blade.php
@extends('admin.master.main')

@section('content')
<div class="title-block">
	<h1 class="title"> Article </h1>
	<p class="title-description"> Index Table Article </p>
	<a href="{{ route('article.create')}}" class="btn btn-info pull-right" style="margin-right:5px;"><em class="fa fa-plus"></em> Add</a>
</div>

@if(session('message'))
  <div class="alert alert-success">
	  {{session('message')}}
  </div>
@endif
<section class="section">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-block">
					<div class="card-title-block">
					</div>
					<section class="example">
						<table class="table table_noxus table-hover">
							<thead>
								<tr>
									<th>Image</th>
									<th>Title</th>
									<th>Type</th>
									<th>Category</th>
									<th>Date</th>
									<th>Tag</th>
									<th>Status</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								@foreach($articles as $article)
								<tr>
									<th><img class="thumb_noxs" src="{{asset('uploads')}}/{{$article->image}}"/></th>
									<th>{{$article->title}}</th>
									<th>{{$article->type}}</th>
									<th>{{$article->category}}</th>
									<th>
										@if($article->date)
										<?php 
											$utcdatetime = $article->date;
										  $datetime = $utcdatetime->toDateTime();
										  $time=$datetime->format('m/d/Y H:m:s');
										?>
										{{$time }}
										@endif
									</th>
									<th>{{$article->tag}}</th>
									<th>{{$article->status ? "Published" : "Unpublished" }}</th>
									<th width="150px;">
										<div class="actions_noxus">
											<a class="button_left" href="{{url('article')}}/{{$article->id}}/edit">
												<button type="button" class="btn btn-pill-left btn-info"><em class="fa fa-pencil-square-o"></em></button>
											</a>
					          	<form class="button_right" role="form" action="{{ route ('article.destroy', $article->id) }}" method="POST">
				            		{!! method_field('DELETE') !!}
					              {!! csrf_field() !!}
										  	<button onclick="return areYouSure(event,this.form)" class="btn btn-pill-right btn-danger" type="submit"><em class="fa fa-eraser"></em></button>
				            	</form>
				            </div>
									</th>
								</tr>
									@endforeach
							</tbody>
						</table>
					</section>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection