routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::middleware(['auth', 'web'])->group(function () {
	Route::get('/', 'HomeController@index')->name('home');
	Route::resource('admin_user', '\App\Http\Controllers\Admin\AdminUser\AdminController');
	Route::resource('article', '\App\Http\Controllers\Admin\Article\ArticleController');
	Route::resource('category', '\App\Http\Controllers\Admin\Category\CategoryController');
	Route::resource('slider', '\App\Http\Controllers\Admin\Slider\SliderController');
	Route::resource('video', '\App\Http\Controllers\Admin\Video\VideoController');
	Route::resource('big_article', '\App\Http\Controllers\Admin\BigArticle\BigArticleController');
	Route::resource('event', '\App\Http\Controllers\Admin\Event\EventController');

	Route::get('get_tab/{id}/{tab_id}/edit/','\App\Http\Controllers\Admin\Event\Tab\TabController@edit')->name('tab.get');
	Route::get('tab/create/{event_id}','\App\Http\Controllers\Admin\Event\Tab\TabController@create')->name('tab.create');
	Route::post('tab/store/{event_id}', '\App\Http\Controllers\Admin\Event\Tab\TabController@store')->name('tab.store');
  //Route::match(['put', 'patch'], 'update_tab/{id}/{tab_id}','\App\Http\Controllers\Admin\Event\Tab\TabController@update')->name('tab.update');
  	Route::post('update_tab/{id}/{tab_id}','\App\Http\Controllers\Admin\Event\Tab\TabController@update')->name('tab.update');

	Route::match(['delete'], 'delete_tab/{event_id}/{tab_id}', '\App\Http\Controllers\Admin\Event\Tab\TabController@destroy')->name('tab.destroy');
});

app/BigArticle.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;
use MongoDB\BSON\UTCDateTime;

class BigArticle extends Model
{
    protected $table = 'articles';

    protected $fillable = ['campaign.name','campaign{name}','type','header_type','category','subcategory','title','campaign','slug','caption','content','campaign{image_mobile}','campaign{image}','published_datetime','status','date','parent_id','tag'];

    public static function getTypeBigArticle(){
    	return Article::where('type','campaign')->orderBy('_id','desc')->get();
    }
}

app/Http/Controllers/Admin/BigArticle/BigArticleController.php
<?php

namespace App\Http\Controllers\Admin\BigArticle;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\BigArticle;
use App\Category;
use Illuminate\Support\Facades\Redirect;
use File;
use Illuminate\Support\Facades\Input;
use MongoDB\BSON\UTCDateTime;

use App\Http\Requests\RequestBigArticle;

class BigArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $big_articles = BigArticle::getTypeBigArticle();
        return view('admin.big_article.index', compact('big_articles'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.big_article.add',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestBigArticle $request)
    {
        $inputs = Input::all();
        $year = date('Y', time());
        $month = date('m', time());
        if($request->date){
        $milliseconds_date = strtotime($request->date);
        $inputs['date'] = new \MongoDB\BSON\UTCDateTime($milliseconds_date *1000);
        }
        $inputs['content'] = $request->mce_0;
        $inputs['type'] = 'campaign';
        $inputs['campaign'] = $request->campaign;
        if($request->hasFile('image')){
          $image = $request->file('image');
          $name = $image->getClientOriginalName();
          $format_folder = $year .'/'.  $month;
          $image_store = $image->storeAs($format_folder . '/', $name , 'pocarisweat');
          $inputs['campaign']['image'] =  $format_folder . '/' . $name;
        }
        if($request->hasFile('image_mobile')){
          $image = $request->file('image_mobile');
          $name = $image->getClientOriginalName();
          $format_folder = $year .'/'.  $month;
          $image_store = $image->storeAs($format_folder . '/', $name , 'pocarisweat');
          $inputs['campaign']['image_mobile'] =  $format_folder . '/' . $name;
        }
        // return $inputs;
        BigArticle::create($inputs);
        return Redirect::route('big_article.index')->with('message', 'Successful Add New Big Article | Campaign');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $big_article = BigArticle::where('_id','=', $id)->first();
        $utcdatetime = @$big_article->date;
        $datetime = ($utcdatetime != null) ? $utcdatetime->toDateTime() : '';
        $time = $datetime != null ? $datetime->format('m/d/Y H:m:s') : '';
        $big_article->date = @$time;
        return view('admin.big_article.edit',compact('big_article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RequestBigArticle $request, $id)
    {
        $big_article = BigArticle::where('_id','=', $id)->first();
        $inputs = Input::all();
        $year = date('Y', time());
        $month = date('m', time());
        $inputs['content'] = $request->mce_0;
        if($request->date){
        $milliseconds_date = strtotime($request->date);
        $inputs['date'] = new \MongoDB\BSON\UTCDateTime($milliseconds_date *1000);
        }
        if($request->hasFile('image')){
          if($big_article->image){
            $old_image = $big_article->image;
            if($old_image){
              $article = BigArticle::findOrFail($id);
              #File::delete('../../api/public/uploads/' . $article->image);
            }
          }
          $image = $request->file('image');
          $name = $image->getClientOriginalName();
          $format_folder = $year .'/'.  $month;
          $image_store = $image->storeAs($format_folder . '/', $name , 'pocarisweat');
          $inputs['campaign']['image'] =  $format_folder . '/' . $name;
        }
        if($request->hasFile('image_mobile')){
          if($big_article->image_mobile){
            $old_image = $big_article->image_mobile;
            if($old_image){
              $article = BigArticle::findOrFail($id);
              #File::delete('../../api/public/uploads/' . $article->image_mobile);
            }
          }
          $image = $request->file('image_mobile');
          $name = $image->getClientOriginalName();
          $format_folder = $year .'/'.  $month;
          $image_store = $image->storeAs($format_folder . '/', $name , 'pocarisweat');
          $inputs['campaign']['image_mobile'] =  $format_folder . '/' . $name;
        }
        $big_article->update($inputs);
        return Redirect::route('big_article.index')->with('message', 'Successful Edit Big Article : ' . @$big_article->campaign['title']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $big_article = BigArticle::where('_id','=', $id)->first();
        if($big_article->image){
          $old_image = $big_article->image;
          if($old_image){
            $article = Article::findOrFail($id);
            #File::delete('../../api/public/uploads/' . $article->image);
          }
        }
        if($big_article->image_mobile){
          $old_image = $big_article->image_mobile;
          if($old_image){
            $article = Article::findOrFail($id);
            #File::delete('../../api/public/uploads/' . $article->image_mobile);
          }
        }
        BigArticle::destroy($id);
        return Redirect::route('big_article.index')->with('message', 'Successful Delete Big Article');
    }
}

resources/views/admin/big_article/add.blade.php
@extends('admin.master.main')

@section('content')
<div class="title-block">
  <h1 class="title"> Create Big Article</h1>
  <p class="title-description"></p>
</div>
@if(session('message'))
    <br/>
  <div class="alert alert-success">
      {{session('message')}}
  </div>
  <br/>
@endif
@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif
<section class="section">
  <div class="row sameheight-container">
    <div class="container-fluid">
        <div class="card card-block">
          <form action="{{action ('Admin\BigArticle\BigArticleController@store')}}" enctype="multipart/form-data" method="POST" role="form">
            {!! csrf_field() !!}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Title</label>
                  <input type="text" name="title" placeholder="" class="form-control underlined" value=""> 
                </div>
                <div class="form-group">
                  <label class="control-label">Campaign Name</label>
                  <input type="text" name="campaign[name]" placeholder="" class="form-control underlined" value=""> 
                </div>
                <div class="form-group">
                  <label class="control-label">Date</label>
                  <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <input  name="date" value="" class="form-control datetimepicker-input underlined" data-target="#datetimepicker1"  />
                    <span class="input-group-addon" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <span class="fa fa-calendar"></span>
                    </span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Caption</label>
                  <input type="text" name="campaign[caption]" placeholder="" class="form-control underlined" value=""> 
                </div>
                <div class="form-group">
                  <label class="control-label">Main Slug</label>
                  <input type="text" name="campaign[slug]" placeholder="" class="form-control underlined" value=""> 
                </div>
                <div class="form-group">
                  <label class="control-label">Sub Slug</label>
                  <input type="text" name="slug" placeholder="" class="form-control underlined" value=""> 
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label">Content</label>
                  <div name="content" class="editor_noxus"></div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Image(1200x530)</label>
                  <input type="file" name="image" placeholder="" class="form-control underlined" value="">
                </div>                
                <div class="form-group">
                  <label class="control-label">Image Mobile(500x650)</label>
                  <input type="file" name="image_mobile" placeholder="" class="form-control underlined" value="">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Header Text</label>
                  <select name="header_type" class="selector_noxus">
                    <option value="" selected>Select Your Header Text</option>
                    <option value="text-right">text-right</option>
                    <option value="text-left">text-left</option>
                    <option value="text-center">text-center</option>
                    <option value="without-text">without-text</option>
                  </select>
                </div>
                <div class="form-group">
                  <label class="control-label">Status</label>
                  <select name="status" class="selector_noxus">
                    <option value="" selected>Select Your Status</option>
                    <option value="1">Published</option>
                    <option value="0">Unpublished</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group pull-right">
                  <button type="submit" class="btn btn-info pull-right"><em class="fa fa-check-square-o"></em> Submit</button>
                  <a href="{{ route('big_article.index') }}" class="btn btn-info pull-right" style="margin-right:5px;"><em class="fa fa-hand-o-left"></em> Cancel</a>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/big_article/edit.blade.php
@extends('admin.master.main')

@section('content')
<div class="title-block">
  <h1 class="title"> Create Big Article</h1>
  <p class="title-description"></p>
</div>
@if(session('message'))
    <br/>
  <div class="alert alert-success">
      {{session('message')}}
  </div>
  <br/>
@endif
@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif
<section class="section">
  <div class="row sameheight-container">
    <div class="container-fluid">
        <div class="card card-block">
          <form action="{{route('big_article.update', $big_article->id)}}" method="POST" enctype="multipart/form-data" role="form">
            {!! method_field('PUT') !!}
            {!! csrf_field() !!}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Title</label>
                  <input type="text" name="title" placeholder="" class="form-control underlined" value="{{ old('title',$big_article->title)}}">
                </div>
                <div class="form-group">
                  <label class="control-label">Campaign Name</label>
                  <input type="text" name="campaign[name]" placeholder="" class="form-control underlined" value="{{old('campaign[name]', $big_article->campaign['name'])}}">
                </div>
                <div class="form-group">
                  <label class="control-label">Date</label>
                  <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <input  name="date" value="{{ old('date',$big_article->date)}}" class="form-control datetimepicker-input underlined" data-target="#datetimepicker1"  />
                    <span class="input-group-addon" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <span class="fa fa-calendar"></span>
                    </span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Caption</label>
                  <input type="text" name="campaign[caption]" placeholder="" class="form-control underlined" value="{{ old('campaign[caption]',$big_article->campaign['caption'])}}">
                </div>
                <div class="form-group">
                  <label class="control-label">Main Slug</label>
                  <input type="text" name="campaign[slug]" placeholder="" class="form-control underlined" value="{{ old('campaign[slug]',$big_article->campaign['slug'])}}">
                </div>
                <div class="form-group">
                  <label class="control-label">Sub Slug</label>
                  <input type="text" name="slug" placeholder="" class="form-control underlined" value="{{ old('slug',$big_article->slug)}}">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label">Content</label>
                  <div name="content" class="editor_noxus">{!! old('content',$big_article->content) !!}</div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="thumb_image cont">
                  <img src="{{asset('uploads')}}/{{@$big_article->campaign['image']}}" alt="" class="thumb_image"/>
                  <span>{{@$big_article->campaign['image']}}</span>
                </div>
                <div class="form-group">
                  <label class="control-label">Image(1200x530)</label>
                  <input type="file" name="image" placeholder="" class="form-control underlined" value="">
                </div>
                <div class="thumb_image cont">
                  <img src="{{asset('uploads')}}/{{@$big_article->campaign['image_mobile']}}" alt="" class="thumb_image"/>
                  <span>{{@$big_article->campaign['image_mobile']}}</span>
                </div>
                <div class="form-group">
                  <label class="control-label">Image Mobile(500x650)</label>
                  <input type="file" name="image_mobile" placeholder="" class="form-control underlined" value="">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label">Header Text</label>
                  <select name="header_type" class="selector_noxus">
                    <option value="{{old('header_type',$big_article->header_type)}}" selected>{{$big_article->header_type}}</option>
                    <option value="text-right">text-right</option>
                    <option value="text-left">text-left</option>
                    <option value="text-center">text-center</option>
                    <option value="without-text">without-text</option>
                  </select>
                </div>
                <div class="form-group">
                  <label class="control-label">Status</label>
                  <select name="status" class="selector_noxus">
                    <option value="{{old('status',$big_article->status)}}" selected>{{$big_article->status ? "Published" : "Unpublished"}}</option>
                    <option value="1">Published</option>
                    <option value="0">Unpublished</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group pull-right">
                  <button type="submit" class="btn btn-info pull-right"><em class="fa fa-check-square-o"></em> Submit</button>
                  <a href="{{ route('big_article.index') }}" class="btn btn-info pull-right" style="margin-right:5px;"><em class="fa fa-hand-o-left"></em> Cancel</a>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/big_article/index.blade.php
@extends('admin.master.main')

@section('content')
<div class="title-block">
	<h1 class="title"> Big Article | Campaign </h1>
	<p class="title-description"> Index Table Big Article or Campaign </p>
	<a href="{{ route('big_article.create')}}" class="btn btn-info pull-right" style="margin-right:5px;"><em class="fa fa-plus"></em> Add</a>
</div>

@if(session('message'))
  <div class="alert alert-success">
	  {{session('message')}}
  </div>
@endif
<section class="section">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-block">
					<div class="card-title-block">
					</div>
					<section class="example">
						<table class="table table_noxus table-hover">
							<thead>
								<tr>
									<th>Title</th>
									<th>Image</th>
									<th>Campaign Name</th>
									<th>Slug</th>
									<th>Date</th>
									<th>Type</th>
									<th>Status</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								@foreach($big_articles as $article)
								<tr>
									<th>{{$article->title}}</th>
									<th><img class="thumb_noxs" src="{{asset('uploads')}}/{{@$article->campaign['image']}}"/></th>
									<th>{{$article->campaign['name']}}</th>
									<th>{{$article->slug}}</th>
									<th>
										@if($article->date)
										<?php
											$utcdatetime = $article->date;
										  $datetime = $utcdatetime->toDateTime();
										  $time=$datetime->format('m/d/Y H:m:s');
										?>
										{{$time }}
										@endif
									</th>
									<th>{{$article->type}}</th>
									<th>{{$article->status ? "Published" : "Unpublished" }}</th>
									<th width="150px;">
										<div class="actions_noxus">
											<a class="button_left" href="{{url('big_article')}}/{{$article->id}}/edit">
												<button type="button" class="btn btn-pill-left btn-info"><em class="fa fa-pencil-square-o"></em></button>
											</a>
					          	<form class="button_right" role="form" action="{{ route ('big_article.destroy', $article->id) }}" method="POST">
				            		{!! method_field('DELETE') !!}
					              {!! csrf_field() !!}
										  	<button onclick="return areYouSure(event,this.form)" class="btn btn-pill-right btn-danger" type="submit"><em class="fa fa-eraser"></em></button>
				            	</form>
				            </div>
									</th>
								</tr>
									@endforeach
							</tbody>
						</table>
					</section>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection